SET TIME ZONE 'UTC';

CREATE TABLE authorizations (
	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	secret BYTEA,
	description TEXT NOT NULL
);

CREATE TYPE image_mode AS ENUM ('scale', 'tile');

-- an image is one or more tiled designs
CREATE TABLE images (
	image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	author_id INTEGER NOT NULL REFERENCES authorizations ON DELETE SET NULL,
	author_name TEXT,
	image_name TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	width SMALLINT,
	height SMALLINT,
	mode image_mode,
	layers BYTEA[] NOT NULL,
	pro BOOLEAN GENERATED ALWAYS AS (array_length(layers, 1) > 1) STORED,
	designs_required SMALLINT GENERATED ALWAYS AS (
		CASE WHEN array_length(layers, 1) > 1 OR mode = 'scale' OR (width = 32 AND height = 32) THEN 1
		ELSE width / 32 * height / 32
		END
	) STORED,

	type_code SMALLINT NOT NULL,

	CHECK (
		(pro AND width IS NULL AND height IS NULL AND mode IS NULL)
		OR (not pro AND width IS NOT NULL AND height IS NOT NULL AND mode IS NOT NULL)
	)
);

CREATE INDEX latest_images ON images (created_at DESC);

-- a design is a single small image uploaded to ACNH servers.
CREATE TABLE designs (
	design_id BIGINT NOT NULL PRIMARY KEY,
	-- no ON DELETE CASCADE because these should be deleted
	image_id INTEGER NOT NULL REFERENCES images,
	-- what position is it in in the original image?
	position SMALLINT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	pro BOOLEAN NOT NULL
);

CREATE INDEX design_sequence_idx ON designs (image_id, position);
-- lets us find which ones to garbage collect
CREATE INDEX oldest_designs ON designs (pro, created_at);

